FROM python:3.6-alpine

RUN adduser -D microblog

WORKDIR /home/microblog

COPY requirements.txt requirements.txt
COPY requirements/* requirements/
COPY Makefile Makefile
COPY test.sh test.sh
COPY pytest.ini pytest.ini
COPY tests/ tests/
COPY .pylintrc .pylintrc

RUN python -m venv venv
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev python-dev py-pip build-base \
  && venv/bin/pip install --upgrade pip \
  && venv/bin/pip install -r requirements/test.txt \
  && apk del build-dependencies

RUN apk update
RUN apk upgrade
RUN apk add make

COPY app app
COPY migrations migrations
COPY microblog.py boot.sh ./
RUN chmod +x test.sh

ENV FLASK_APP microblog.py

RUN chown -R microblog:microblog ./
USER microblog
RUN cd tests ls -l

ENTRYPOINT ["./test.sh"]
